autokitteh/vscode-extension

- src/controllers/project.controller.ts
- src/enums/index.ts
- src/enums/sessionStates.enum.ts
- src/i18n/en/errors.i18n.json
- src/i18n/en/sessions.i18n.json
- src/models/error.model.ts
- src/models/index.ts
- src/models/sessionLogRecord.model.ts
- src/models/sessionState.model.ts
- src/models/utils/sessionsStateConverter.utils.ts
- src/services/projects.service.ts
- src/services/sessions.service.ts
- src/types/models/deployment.type.ts
- vscode-react/src/sections/aKDeployments.section.tsx
> fix: display of the session logs with the new backend

- package.json
- src/constants/vsCommands.constants.ts
- src/controllers/project.controller.ts
- src/controllers/sidebar.controller.ts
- src/controllers/tabsManager.controller.ts
- src/controllers/utilities/appStateHandler.ts
- src/controllers/utilities/index.ts
- src/extension.ts
- src/i18n/en/projects.i18n.json
These days, we are not considering the app state for the server requests.
This PR fixes this problem.
https://linear.app/autokitteh/issue/UI-172/fix-stop-requests-on-disconnect
> fix: app-state-handler intervals control

- .husky/commit-msg
> style: fix husky hook for the pre-commit/push

- src/utilities/fileSystem.utils.ts
- src/utilities/index.ts
> fix: fix relative path in filesSystem utils

- src/services/deployments.service.ts
- src/services/projects.service.ts
Add try-catch blocks in the missing calls in services.
> fix: add missing try-catch to services

- package.json
Restore the ability to deploy and build projects from the projects sidebar.
> fix: fix missing buttons in the projects list

- src/utilities/fileSystem.utils.ts
Fix paths issue on windows.
Current function (`path.relative`) doesn't handle paths of windows, therefore we need to normalize it.
> fix: paths issue on windows

- vscode-react/src/components/aKSessionTableBody.component.tsx
- vscode-react/src/components/akMonacoEditorModal.component.tsx
- vscode-react/src/sections/aKSessions.section.tsx
fix singleshot parameters display
> fix: fix singleshot ui

- .github/pull_request_template.md
Improve our PR Template by adding our code standards to it.
> docs: update pr template to contain our code standards

- resources/yaml-autocompletion-scheme/manifest.schema.json
> chore: update ak-yaml manifest

- src/utilities/vsCodeMessageHandler.utils.ts
Fix the notification level getter.
> fix: fix the notification-level getter

- src/controllers/project.controller.ts
- src/enums/messageType.enum.ts
- src/i18n/en/reactApp/deployments.reactApp.i18n.json
- src/i18n/en/reactApp/sessions.reactApp.i18n.json
- src/interfaces/projectView.interface.ts
- src/utilities/vsCodeMessageHandler.utils.ts
- src/views/project.view.ts
- vscode-react/src/components/aKDeploymentTableBody.component.tsx
- vscode-react/src/components/aKSessionTableBody.component.tsx
Disable delete buttons for deployments/sessions if the deployment is active or the session running
> fix: disable delete buttons in case deployment is active or session is running

- package.json
change naming convention to enable-disable
> chore: change naming convention to enable-disable

- src/services/starlark/starlarkVersionManager.service.ts
> style: prettier starlark file

- src/controllers/project.controller.ts
VSCode - Don't ask for resources before local directory selected: 
Remove the download resources dialog before the user selects the local directory.
After the user chooses the directory - the resources will be downloaded automatically.
https://linear.app/autokitteh/issue/UI-225/vscode-dont-ask-for-resources-before-local-directory-selected
> refactor: remove download resources message before directory selected

- src/controllers/project.controller.ts
- src/enums/messageType.enum.ts
- src/i18n/en/errors.i18n.json
- src/i18n/en/reactApp/settings.reactApp.i18n.json
- src/interfaces/projectView.interface.ts
- src/utilities/archive.utils.ts
- src/utilities/fileSystem.utils.ts
- src/utilities/index.ts
- src/views/project.view.ts
- vscode-react/src/components/aKDirectoryDownloadPopper.component.tsx
Open file explorer for the projecr resources directory.
https://linear.app/autokitteh/issue/UI-221/vscode-open-explorer-window-where-we-display-path-info-for-any-project
> feat: open directory of project resources from the webview

- vscode-react/src/components/aKDeploymentTableBody.component.tsx
- vscode-react/src/components/aKDeploymentTableHeader.component.tsx
- vscode-react/src/components/aKSessionTableBody.component.tsx
- vscode-react/src/components/akMonacoEditorModal.component.tsx
* Align sessions and deployments buttons
* Background behind props for sessions modal transparent
https://linear.app/autokitteh/issue/UI-220/vscode-ui-touch-up
Buttons alignment:
Session props modal:
> refactor: ui touch-ups

- src/controllers/project.controller.ts
- src/i18n/en/errors.i18n.json
- src/i18n/en/projects.i18n.json
Fix i18n definitions for projects actions
> refactor: fix i18n definitions

- vscode-react/src/components/aKProjectSettingsPopper.component.tsx
Set constant width for the settings popper.
> refactor: popper design

- src/extension.ts
Display starlark error - title only, without the error.
> refactor: starlark error fix

- src/controllers/project.controller.ts
- src/views/project.view.ts
Fix an issue which was caused by sending the project name before the webview was initialized.
https://linear.app/autokitteh/issue/UI-186/vscode-bug-windows-starlarklsp-wont-start
> fix: fix stuck loading screen on project open in windows

- .vscodeignore
- package-lock.json
- package.json
- vscode-react/.gitignore
- vscode-react/package.json
- vscode-react/vite.config.mts
* Make manipulations in order to reduce the bundle size, because the current size is way too large (45 MB).
* Add tools to check and reduce the size in the future even more.
https://linear.app/autokitteh/issue/UI-233/reduce-bundle-size-of-the-extension
> feat: reduce bundle size

- src/services/sessions.service.ts
Fix bad import in sessions service.
> refactor: fix import in sessions service

- src/controllers/project.controller.ts
- src/i18n/en/errors.i18n.json
- src/models/sessionLogRecord.model.ts
- src/services/builds.service.ts
- src/services/deployments.service.ts
- src/services/environments.service.ts
- src/services/sessions.service.ts
Apply PullRequests comments from: https://github.com/autokitteh/web-platform/pull/69
https://linear.app/autokitteh/issue/UI-212/cloud-update-ak-models-services
> refactor: optimize services

- src/i18n/en/reactApp/settings.reactApp.i18n.json
- vscode-react/src/app.tsx
> refactor: update button title

- package.json
https://linear.app/autokitteh/issue/UI-261/remove-irrelevant-actions-from-command-pallete
**Before:**
**After:**
> refactor: hide irrelevant commands from the command pallete (UI-261)

- .github/workflows/build_test_and_release_app.yml
Release new version to extension market on merge to the main using: 
https://github.com/marketplace/actions/github-action-for-vsce
https://linear.app/autokitteh/issue/UI-262/vs-release-vscode-publish-on-merge-to-main
> feat: release new version to extension market on merge to main (UI-262)

- vscode-react/src/components/akMonacoEditorModal.component.tsx
- vscode-react/tailwind.config.js
> refactor: tailwind color nit fix

- package.json
Basing on [this comment:](https://github.com/microsoft/vscode-notebook-renderers/issues/150#issuecomment-1839188186), added `activationEvents` as an empty array in package.json.
Basing on those files:
* https://github.com/microsoft/vscode-vsce/blob/af201cd4dfb05c24bb853c1e3034fb1224b81467/src/manifest.ts#L77
* https://github.com/microsoft/vscode-vsce/blob/af201cd4dfb05c24bb853c1e3034fb1224b81467/src/test/fixtures/nls/package.json#L71
I placed the `activationEvents` property as an empty array on the top-level in package.json, and not in the `contributes` section.
https://linear.app/autokitteh/issue/UI-262/vs-release-vscode-publish-on-merge-to-main
> fix: modify package.json to fix to vscode marketplace publish on merge to main (UI-262)

- package.json
In the last action, the extension icon was missing, fixed the paths with `./` in package.json:
https://github.com/autokitteh/vscode-extension/actions/runs/8833601820/job/24253349058
https://linear.app/autokitteh/issue/UI-262/vs-release-vscode-publish-on-merge-to-main
> fix: publish to marketplace - icon issue

- src/controllers/project.controller.ts
- src/enums/messageType.enum.ts
- src/interfaces/projectView.interface.ts
- src/views/project.view.ts
- tests/mocks/viewInterface.mock.ts
- vscode-react/src/sections/aKDeployments.section.tsx
> fix: project deployments doesn't load on project open

- src/controllers/project.controller.ts
Remember the last deployment and session the user chose in his last interaction with the project. 
https://linear.app/autokitteh/issue/UI-283/save-selected-session-and-deployments-selection-on-project-change
> fix: save selected session and deployments on project change (UI-283)

- package-lock.json
- vscode-react/package.json
https://linear.app/autokitteh/issue/UI-289/allow-react-build-on-windows-esbuild-adjustment
> chore: add esbuild to run react app on windows (UI-289)

- src/controllers/project.controller.ts
When we display logs of finished sessions, such as completed/errored/stopped, we can save it logs in our state so next time when we want to display the logs, we won't need to request the server again.
https://linear.app/autokitteh/issue/UI-284/save-logs-for-completederrrored-sessions-in-the-state-to-display-on
> refactor: cache session logs when session finished (UI-284)

- package.json
Add auth-token field in extension settings - initiation.
https://linear.app/autokitteh/issue/UI-293/configurable-token
> feat: add auth-token field in extension settings (UI-293)

- .github/workflows/build_test_and_release_app.yml
Add missing env-var to the build&release workflow.
> ci: fix build and release workflow

- .github/workflows/deploy_release_to_marketplace.yml
debug vscode marketplace workflow
> ci: debug vscode marketplace workflow

- .github/workflows/deploy_release_to_marketplace.yml
debug vscode marketplace workflow - follow redirect to cURL flag
> ci: debug vscode marketplace workflow - follow redirect to cURL flag

- package.json
fix: fix engine version to match it to the @types/vscode in the previous release.
> fix: fix engine version to match it to the @types/vscode

- src/controllers/project.controller.ts
- src/models/sessionLogRecord.model.ts
> fix: session logs model fix to handle error bug in some sessions

- package-lock.json
Fix vscode engine version in package-json.lock
> chore: fix vscode engine version in package-json.lock

- .github/workflows/deploy_release_to_marketplace.yml
Fix the ability to publish the extension as a pre-release using GitHub actions.
https://linear.app/autokitteh/issue/UI-337/fix-publish-to-vscode-marketplace-pre-release
> fix: fix publish pre-release workflow

- .github/workflows/deploy_release_to_marketplace.yml
fix publish workflow - fix git-submodule call
> ci: fix publish workflow - fix git-submodule call

- CONTRIBUTING.md
- README.md
update README.md file with the relevant changes.
> docs: update readme file

- src/controllers/project.controller.ts
- src/controllers/sidebar.controller.ts
Bug:
Many requests are being sent to the server and the loading state won't stop when the project window is being un-focused or blured.
> fix: stop intervals on project window blur

- src/controllers/project.controller.ts
- src/models/views/sessionsView.model.ts
- vscode-react/src/components/sessions/pages/sessionsSection.component.tsx
avoid ui issues working with deployments and sessions
> fix: avoid ui issues working with deployments and sessions

- .github/workflows/build_and_compile.yml
Rephrase workflow name to a proper one.
> refactor: correct workflow name

- src/controllers/project.controller.ts
Bug: 
When we're moving between projects - the sessions log is not being cleared, and when we re-open a project, it's being printed again.
Video:
https://github.com/autokitteh/vscode-extension/assets/7413072/b5ad0002-a014-45b6-947b-e8bf689b601e
https://linear.app/autokitteh/issue/UI-372/sessions-printed-twice-moving-between-projects
> fix: clear sessions output when we're moving between projects

- .github/workflows/deploy_release_to_marketplace.yml
Remove git-tag from the publish workflow
> ci: remove git-tag from the publish workflow

- .github/workflows/deploy_release_to_marketplace.yml
add github token to the publish workflow
> ci: add github token to the publish workflow

- .github/workflows/deploy_release_to_marketplace.yml
- release.config.js
> ci: fix publish workflow

- .github/workflows/deploy_release_to_marketplace.yml
- release.config.js
Key Adjustments:
1. CLI Branch Configuration: The branches are specified directly in the CLI command, ensuring the correct configuration is used based on the release-type input.
2. Simplified release.config.js: Since the branches are being specified via CLI, there's no need to handle them within the release.config.js.
3. This setup should correctly handle both pre-releases and regular releases based on your input in the GitHub Actions workflow.
> ci: fix publish workflow - use cli

- .github/workflows/deploy_release_to_marketplace.yml
- release.config.js
Fixed the workflow with this answer: https://stackoverflow.com/a/65009379
> ci: fix publish workflow - add another branch

- release.config.js
fix publish workflow - remove rc suffix
> ci: fix publish workflow - remove rc suffix

- release.config.js
fix publish workflow - with additional branch
> ci: fix publish workflow - with additional branch

- .github/workflows/build_and_compile.yml
- .github/workflows/deploy_release_to_marketplace.yml
- release.config.js
Change back the code to create only version with running numbers as described in the vscode market place versioning recommendation here: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions.
> ci: fix publish workflow for semantic-release and vscode market place

- src/controllers/project.controller.ts
- src/i18n/en/reactApp/sessions.reactApp.i18n.json
- src/i18n/en/sessions.i18n.json
- src/views/project.view.ts
- vscode-react/src/components/sessions/molecules/sessionActions.component.tsx
- vscode-react/src/components/sessions/organisms/sessionsTableBody.component.tsx
- vscode-react/src/types/sessions.type.ts
- vscode-react/src/utilities/sessions.utils.ts
Fix (block) session deletion in case the status of it is stopped.
Fix successfully deleted session message.
Add missing break in project view.
https://linear.app/autokitteh/issue/UI-375/active-tab-after-refresh-page
> fix: block session deletion in case the status of it is stopped and correct the deletion message

- release.config.js
Before this commit, semantic-release was commenting the word "true" on released PRs, as we can see here:
https://github.com/autokitteh/vscode-extension/pull/342
In order to make it understandable, I added a proper message to `@semantic-release/github` add-on, and used it as described here:
https://github.com/semantic-release/github?tab=readme-ov-file#successcomment
https://linear.app/autokitteh/issue/UI-390/rephrase-semantic-release-success-comment-on-released-prs
> chore: rephrase semantic release success comment on released pr

- src/extension.ts
- vscode-react/vite.config.mts
> refactor: fix compilation

- package.json
- src/controllers/project.controller.ts
- src/controllers/sidebar.controller.ts
- src/controllers/utilities/appStateHandler.ts
- src/controllers/utilities/resources.util.ts
- src/extension.ts
- src/i18n/en/general.i18n.json
- src/i18n/en/projects.i18n.json
- src/views/sidebar.view.ts
- src/vscommands/applyManifest.vscommands.ts
- src/vscommands/setToken.vscommands.ts
- Change the scope of a few properties to `machine` to preserve them when we move between workspaces:
-- starlark path
-- starlark version
-- project files directories paths
- Display host URL in the projects bar
> feat: change settings to machine level and display host url

- package.json
add the host url to the machine-scoped settings
> fix: add the host url to the machine scoped settings as well

- release.config.js
Bump version in the publishing workflow (semantic-release used only in this workflow) in case nothing changes.
For example - we published some version to the pre-release marketplace, tested it, and now we want to publish it as the main release version, but we can't, since we don't have new commits, and the vscode marketplace doesn't allow to publish same versions, even if it's different releases.
> ci: bump version even if there are no new commits

- package-lock.json
- package.json
install missing package for semantic-release
> ci: install missing package for semantic-release

- src/extension.ts
Fix - get/set starlark path to the global context.
> fix: not saved starlark lsp path

- src/extension.ts
- src/i18n/en/general.i18n.json
Reload extension in order to reload the context of the vscode, to have the latest changes.
> fix: reload after starlark installed

- package-lock.json
Keep our app updated with the latest versions to keep it safe.
> perf: update braces dependency in package-lock to improve security

- src/models/connection.model.ts
Fix the format of the connection init url for connections.
> fix: fix link of the final init connection-url

- package.json
- src/constants/vsCommands.constants.ts
- src/extension.ts
- src/vscommands/sideBarActions/addConnections.vscommands.ts
- src/vscommands/sideBarActions/index.ts
Remove the connections button, because the ways we can add a connection are: CLI, Apply Manifest (VSCode), and SaaS (WebUI) - therefore the connections button isn't relevant.
> refactor: remove open connections page button from the sidebar

- src/controllers/sidebar.controller.ts
- src/controllers/tabsManager.controller.ts
- src/extension.ts
- src/views/sidebar.view.ts
Stop timers on the extension exit.
> fix: clean running processes when we close the extension

- package.json
- src/i18n/en/manifest.i18n.json
- src/vscommands/applyManifest.vscommands.ts
Until now we could run the Apply Manifest command on every open file in VSCode.
Now we have 2 options:
1. If we open VSCode on a file that is not YAML, the command palette shouldn't suggest the Apply Manifest command since we added a filter.
2. If we run the Apply Manifest command on a YAML file, and the command appears in our recently used commands, we can't filter it, but we can check the extension of the file we trying to apply. I added a check that stops the action in case the file is not YAML.
The solution should prevent this ticket using the extension: 
https://linear.app/autokitteh/issue/ENG-1240/trying-to-apply-manifest-with-starlark-file-the-error-is-not-clear
> feat: block apply-manifest on non-yaml files

- .eslintrc.json
- package.json
- src/constants/vsCommands.constants.ts
- src/controllers/connections.controller.ts
- src/controllers/project.controller.ts
- src/eventEmitter.ts
- src/extension.ts
- src/i18n/en/connections.i18n.json
- src/i18n/en/errors.i18n.json
- src/i18n/en/index.ts
- src/interfaces/projectView.interface.ts
- src/services/connections.service.ts
- src/views/project.view.ts
- tsconfig.json
- vscode-react/src/components/connections/organisms/connectionsModal.component.tsx
Update single connection status when the user completes successful connection initiation.
https://linear.app/autokitteh/issue/UI-399/vscode-connection-init-magic-link
> feat: handle incoming vscode:// urls into vscode

- src/controllers/project.controller.ts
When we delete deployments, we want the sessions view to reset as well.
https://linear.app/autokitteh/issue/UI-521/vscode-stopped-and-deleted-session-ghost
> fix: reset sessions view after removing deployment

- .vscode/launch.json
- .vscode/tasks.json
- package-lock.json
- package.json
**The bug:**
When we run debug mode for our extension and change the code, the UI won't stop in the breakpoints until we won't delete the dist folder + won't run build + run compile, the code won't take the latest version and the breakpoints won't stop.
**The fix:**
Add prebuild task, which deletes and re-compiles the distribution files, meaning on each run/re-run action in the VSCode debugger, it will re-build and will allow us to see the most recent code.
> fix: rebuild in debug mode

- src/controllers/utilities/convertBuildRuntimesToViewTriggers.utils.ts
- src/i18n/en/reactApp/deployments.reactApp.i18n.json
- vscode-react/src/components/deployments/organisms/executePopper.component.tsx
Fix duplicates entry points
https://linear.app/autokitteh/issue/UI-570/filter-out-functions-begininng-with-underscore-or-archive
https://linear.app/autokitteh/issue/UI-569/fix-entry-points-functions-duplicates
> refactor: processRuntime function

- README.md
- docs/extension-structure.md
1. Add an explanation of how to run the project development
2. Remove redundant and incorrect information
https://linear.app/autokitteh/issue/UI-695/improve-documentation-for-vscode-extension
> chore: update readme file with additional information

- package.json
- src/constants/api.constants.ts
Our need:
* if the backend is at api.autokitteh.cloud, automatically set the ui to app.autokitteh.cloud
* if it's anything else at x-api.autokitteh.cloud, set the ui x.autokitteh.cloud
* for local or if the webInterfaceURL is not defined or is an empty string set the default to http://localhost:9982
https://linear.app/autokitteh/issue/UI-707/vscode-point-connections-to-the-webui
> feat: add connections web-ui url getter

- src/constants/extensionConfiguration.constants.ts
- src/constants/index.ts
- src/controllers/project.controller.ts
- src/controllers/utilities/convertBuildRuntimesToViewTriggers.utils.ts
- src/i18n/en/reactApp/deployments.reactApp.i18n.json
- src/interfaces/projectView.interface.ts
- src/services/sessions.service.ts
- src/types/index.ts
- src/types/startSessionArgs.type.ts
- src/views/project.view.ts
- vscode-react/src/components/deployments/index.ts
- vscode-react/src/components/deployments/organisms/deploymentsTableBody.component.tsx
- vscode-react/src/components/deployments/organisms/executePopper.component.tsx
- vscode-react/src/components/deployments/organisms/index.ts
- vscode-react/src/components/deployments/organisms/manualRunPopper.component.tsx
- vscode-react/src/components/molecules/popper.component.tsx
- vscode-react/src/hooks/useIncomingMessageHandler.hook.ts
- vscode-react/src/interfaces/incomingMessagesHandler.interface.ts
Because of the recent changes in the backend Python, re-written the manual run functionality:
- Added parameters to manual run.
- Switch function name dropdown to text input
> fix: manual execution

- src/services/sessions.service.ts
- src/utilities/index.ts
- src/utilities/omit.utils.ts
- vscode-react/assets/icons/triggers.icon.tsx
- vscode-react/src/components/organisms/header.component.tsx
The extension was crashing because we used library that not installed in package.json (lodash).
> fix: complete missing omit function from lodash

- src/services/projects.service.ts
Switch listForOwner to list in projects API because listForOwner is deprecated.
https://linear.app/autokitteh/issue/UI-1097/switch-listforowner-to-list-in-projects-api
-   [ ] 💡 (feat) - A new feature (non-breaking change which adds functionality)
-   [ ] 🔄 (refactor) - Code Refactoring - A code change that neither fixes a bug nor adds a feature
-   [x] 🐞 (fix) - Bug Fix (non-breaking change which fixes an issue)
-   [ ] 🏎 (perf) - Optimization
-   [ ] 📄 (docs) - Documentation - Documentation only changes
-   [ ] 📄 (test) - Tests - Adding missing tests or correcting existing tests
-   [ ] 🎨 (style) - Styles - Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
-   [ ] ⚙️ (ci) - Continuous Integrations - Changes to our CI configuration …
> fix(UI-1097): switch projects list request

- src/extension.ts
When we change server (url+token) we can't work anymore.
https://linear.app/autokitteh/issue/UI-1320/vscode-fix-organizations-change
> fix(UI-1320): fix host change

- src/controllers/project.controller.ts
Sometimes when we go from project to file, from project to project, and back, the deployments state inside the controller doesn't reset and since the new deployments are equal to the local `this.deployments` the view doesn't update and we see only "Loading..." instead of the deployments. 
https://linear.app/autokitteh/issue/UI-1318/vscode-deployments-stuck-on-loading-when-you-move-from-the-project-to
> fix(UI-1318): fix deployments stuck on loading on tab focus

- src/i18n/en/manifest.i18n.json
- src/i18n/en/projects.i18n.json
- src/services/projects.service.ts
- src/vscommands/applyManifest.vscommands.ts
This PR enhances the `applyManifest` command to automatically save/upload project files after successfully applying a manifest.
- Enhanced `applyManifest.vscommands.ts` to automatically upload project files after manifest application
- Added `setResources` method to `ProjectsService` for uploading files to projects via gRPC
After successful manifest application, the command now:
1. Identifies the project ID associated with the manifest directory
2. Collects all local project resources using existing `getLocalResources` utility
3. Filters out `autokitteh.yaml` from the upload (manifest file itself)
4. Uploads remaining files to the project using the new `setResources` service method
- **Streamlined workflow**: applying a manifest now automatically syncs local files
- **Reduced manual …
> feat(UI-1883): update files on server when user runs apply-manifest
