autokitteh/vscode-extension

src/services/starlark/starlarkVersionManager.service.ts
Temporary patch, the platform as defined in NodeJS has only one option for windows: "win32".
On the other hand, in our [backend executable](https://github.com/autokitteh/autokitteh/releases/tag/v0.3.1) the architecture is defined as "windows".
Therefore, we need this adjustment.
https://linear.app/autokitteh/issue/UI-190/vscode-adjust-the-starlarklsp-executable-to-a-relevant-platform-by
=> fix: starlark needed executable recognition on windows

package.json, src/utilities/vsCodeMessageHandler.utils.ts
* Allow the user to control the level of notification that he wants to see: All notifications, errors only, or none.
=> feat: control notifications level in extension settings

src/controllers/project.controller.ts
**The issue:**
When we had a running session, we changed the selection to another (completed) session and swapped back to the running session, the log was not changed back to the running, until the next update of the running session.
**The fix:**
Reset the sessionHistoryStates state on the session selection change.
https://linear.app/autokitteh/issue/UI-206/vscode-display-session-history-when-switching-to-running-session
=> fix: display session history when switching to running session

src/controllers/sidebar.controller.ts, src/i18n/en/general.i18n.json, src/i18n/en/projects.i18n.json, src/views/sidebar.view.ts
Display proper message when the connectivity with the server fails.
Before:
After:
https://linear.app/autokitteh/issue/UI-205/vscode-display-an-appropriate-message-on-extension-disconnection
=> fix: display appropriate message on reconnecting status

src/services/starlark/starlarkVersionManager.service.ts, src/utilities/archive.utils.ts, src/utilities/fileSystem.utils.ts, src/utilities/index.ts
In past pull requests, we modified the createDirectory to throw a message when the directory exists.
It works for us to create a directory for the "pull-resources-from-the-server" feature, but it doesn't fit when we should download starlarkLSP, because in case we want to download starlarkLSP, and we don't have locally the LSP file, but we do have the directory, we still would like to download the LSP file into the directory.
In other words:
When we had Starlark only - we used createDirectory and if the directory existed, it didn't matter, because even if the folder existed, we knew that the Starlark file was missing and we should download it to the directory.
*Directory Exist -> no error thrown, don't care*
2. When we developed DownloadResources - if the directory exists - it matters …
=> fix: fix starlark download when the folder is already exist

.prettierignore, package-lock.json, vscode-react/package.json, vscode-react/src/app.css, vscode-react/src/app.tsx, vscode-react/src/components/AKTable/aKTableHeaderCell.component.tsx, vscode-react/src/components/aKDeploymentTableHeader.component.tsx, vscode-react/src/components/aKSessionTableBody.component.tsx, vscode-react/src/components/aKSessionTableHeader.component.tsx, vscode-react/src/components/akMonacoEditorModal.component.tsx, vscode-react/src/sections/aKDeployments.section.tsx, vscode-react/src/sections/aKSessions.section.tsx
Allow users to move the border between sessions and deployments split.
Demonstration:
https://github.com/autokitteh/vscode-extension/assets/7413072/ddcd2316-fb9a-4ec9-9aae-cacbf284fd0f
https://linear.app/autokitteh/issue/UI-228/add-ability-of-pane-pull-between-sessions-and-deployments
=> feat (UI-228): react split pane

vscode-react/src/components/aKDeploymentTableBody.component.tsx, vscode-react/src/components/aKDeploymentTableHeader.component.tsx, vscode-react/src/components/aKOverlay.component.tsx, vscode-react/src/components/aKPopper.component.tsx, vscode-react/src/components/aKSessionTableBody.component.tsx, vscode-react/src/components/aKSessionTableHeader.component.tsx, vscode-react/src/sections/aKDeployments.section.tsx, vscode-react/src/sections/aKSessions.section.tsx
Since the deployments & sessions tables were locked inside the new panes for the main screen, we had to set-up the z-index properties for them, send them to the top level with `createPortal`.
=> fix: poppers and overlays weren't displayed properly because of the split-pane feature

src/i18n/en/errors.i18n.json, src/models/sessionLogRecord.model.ts
The backend structure of the session log record has been changed, now we don't have only one key per session log, but `processId` also.
Because of this, we have to find the needed key and not assume it's the only one and located at the first index of props.
=> fix: get session log record type by the new structure from the ak backend

src/controllers/project.controller.ts
Fix logger namespaces in the project controller from session service to project controller.
https://linear.app/autokitteh/issue/UI-260/fix-logger-namespaces-in-project-controller
=> refactor: update logger namespaces in project controller (UI-260)

package.json
In the last week @ig-ra  paid attention that if he disable all extensions on VSCode except autokitteh, it disables as well.
The issue was that autokitteh had a dependency on the redhat-yaml extension and when it wasn't enabled, autokitteh turned off as well.
We don't need that dependency, since it's nice to have extension with autokitteh, to have yaml files syntax, but it's not a must.
Therefore it should be removed as a dependency.
https://linear.app/autokitteh/issue/UI-258/remove-redhat-yaml-extension-dependency
=> fix: remove redhat-yaml extension dependency (UI-258)

src/controllers/project.controller.ts, src/enums/projectRecurringErrors.enum.ts, src/i18n/en/errors.i18n.json
In order to avoid selected session change every second in a case when many sessions are coming every second, in our case disabled the latest session selection on sessions change.
https://linear.app/autokitteh/issue/UI-237/sessions-logs-on-load-doesnt-load-well
https://github.com/autokitteh/vscode-extension/assets/7413072/5f42d588-580b-4cd2-af56-ce2f09010478
=> feat: disable session auto-select the last one on change (UI-237)

src/controllers/project.controller.ts, src/enums/projectRecurringErrors.enum.ts, src/i18n/en/errors.i18n.json
Session log re-fetching only in one case - when the session is running, there we should disable the repeating notifications displayed to the user.
https://linear.app/autokitteh/issue/UI-259/avoid-repeating-notifications-when-session-log-re-fetching-on-interval
=> fix: avoid repeating notifications when session history pulled on server down  (UI-259)

package-lock.json, package.json
This action run: https://github.com/autokitteh/vscode-extension/actions/runs/8832630055/job/24251667903#step:8:1
Complains that `Manifest needs the 'activationEvents' property, given it has a 'main' property.`, in order to fix, removed the `activationEvents` field from the package.json file.
https://linear.app/autokitteh/issue/UI-262/vs-release-vscode-publish-on-merge-to-main
=> fix: modify package.json to fix release on merge to main

vscode-react/src/components/sessions/pages/sessionsSection.component.tsx, vscode-react/src/context/appState.context.tsx
Increase loader delay and remove loading state from the sessions view
https://linear.app/autokitteh/issue/UI-336/reduce-sessions-flakyness
=> fix: remove loading state from sessions view

src/controllers/project.controller.ts, src/enums/messageType.enum.ts, vscode-react/src/components/sessions/pages/sessionsSection.component.tsx, vscode-react/src/hooks/useIncomingMessageHandler.hook.ts, vscode-react/src/interfaces/incomingMessagesHandler.interface.ts
Bug:
Live-tail button is not displayed when we:
1. Choose the active deployment
2. Stop the live tail in it
3. Choose another deployment
4. Go back to the active deployment
Fix:
Set the live tail button visibility state every time we choose deployment, by it state (is active or draining).
=> fix: live-tail button not displayed after choosing another deployment

src/controllers/project.controller.ts
**Bug:**
We run `buildInfo` of the latest build, to display its functions in the deployment, and every project window focus/unfocus/deployments change which causes redundant calls to the server.
**Recommended solution:**
Fetch it only on project load or when we create a new deployment.
https://linear.app/autokitteh/issue/UI-543/fix-redundant-buildinfo-fetching
=> fix: Avoid fetching build-info on each project load

src/controllers/project.controller.ts
Current bug: when you open a project without local files, it doesn't activate build & deploy buttons, while it should.
https://linear.app/autokitteh/issue/UI-603/reload-ui-buttons-build-and-deploy-when-you-pick-resources-folder
=> fix: activate build and deploy buttons when resources downloaded

package.json, src/constants/api.constants.ts, src/constants/index.ts, src/controllers/connections.controller.ts, src/interfaces/projectView.interface.ts, src/views/project.view.ts, vscode-react/src/components/connections/organisms/connectionsModal.component.tsx
In the VSCode extension in the connection modal change the init URL from: http://localhost:9980/connections/con_01j9tng29ffp89djt2zf3qqb3r/init/vscode -> http://localhost:9982/projects/prj_01j9tng290fvpapn0et43n5eq4/connections/con_01j9tng29ffp89djt2zf3qqb3r/edit
From: http://HOST_URL/connections/con_01j9tng29ffp89djt2zf3qqb3r/init/vscode
To: http://WEB_UI_URL/projects/{projectId}/connections/{connectionId}/edit
https://linear.app/autokitteh/issue/UI-707/vscode-point-connections-to-the-webui
=> feat: move the connections init to local web-ui

src/controllers/project.controller.ts, vscode-react/src/components/deployments/organisms/deploymentsTableBody.component.tsx
Bug:
When you open a project, go to another tab, back to the project, there are no files in the manual run pop-up window.
https://linear.app/autokitteh/issue/UI-804/re-fetch-files-for-manual-run-on-project-enable-focus-or-re-open
=> fix: re-fetch files for manual run on project enable (focus or re-open)

src/controllers/project.controller.ts
On the following flow:
1. Open a project
2. Move to another tab (another project or a code file)
3. Back to the project tab
We were fetching the deployments from the backend twice: the first time in the `enable` function which is triggered `onFocus`, and the second time in `loadInitialDataOnceViewReady` when the `deploymentsSection` component was successfully mounted. On the second time, we weren't sending it to the UI, because of this condition `if (isEqual(this.deployments, deployments))` but the extension was sending the requests for the deployments list twice.
The change protects the `loadInitialDataOnceViewReady` function from running together with `enable` and `onFocus` and runs only once - when the project opens for the first time.
=> fix(UI-1412): deployments fetch optimization on project tab focus
